# Podfile content
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'MyShop' do
  react_native_path = "../node_modules/react-native"
  pod "Yoga", :path => "#{react_native_path}/ReactCommon/yoga"
  pod "React", :path => react_native_path

  pod 'GoogleMaps'  # <~~ remove this line if you do not want to support GoogleMaps on iOS

end